### PR TITLE
Complete ProductPage.qml, SettingsAccount.qml, Add Icons.qml to use SVG Icons.

### PR DESCRIPTION
**Pull request by rnayabed**
Completed ProductPage.qml as per #20 

image
image

It has been provided with models and functions that can be easily invoked/accessed with the equivalent C++ controller.
For now, sample placeholder values have been provided.

### CODE REVIEW

**Comment by rnayabed** [comment]
In the screenshots, the `ApplicationWindow` version of it has been shown. It has been provided as an `Item` in the PR, hence can be used as dialog/popup within the parent window or a separate window too.

**Comment by larteyoh** [comment]
Alright. I'm a bit late to the party, but I'll check it out now.

**Comment by rnayabed** [comment]
Hmm this is weird. Can you tell which version of Qt you're running this on?

**Comment by larteyoh** [comment]
These are pretty minor issues, but you forgot to add these lines to the qml.qrc file:
```
        <file>qml/components/Rating.qml</file>
        <file>qml/components/RatingStar.qml</file>
```

and `import FontAwesome 1.0` in RatingStar.qml

I caught another error:
`qrc:/qml/pages/ProductPage.qml:449:29: Unable to assign [undefined] to QString`

These aren'r as big of a deal though. I also understand that you were not able to build Monero which is the reason for these minor issues.

**Comment by rnayabed** [comment]
I'm aware of these issues actually and have been refactoring and cleaning up this + working on account settings. Will update this PR when it's done :)

**Pull request closed without merging**
